name: whylowdps

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=whylowdps
      - POSTGRES_PASSWORD=whylowdps
      - POSTGRES_DB=whylowdps
    ports:
      - "5432:5432"
    volumes:
      - whylowdps-db-data:/var/lib/postgresql/data

  backend:
    build:
      context: backend
      dockerfile: server/Dockerfile
      args:
        - SIMC_VERSION=${SIMC_VERSION:-HEAD}
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATA_DIR=/app/resources/data
      - DATABASE_URL=postgres://whylowdps:whylowdps@db:5432/whylowdps
      - PORT=8000

  frontend:
    build:
      context: frontend
      args:
        - NEXT_PUBLIC_API_URL=https://${SERVER_IP:-localhost}
        - INTERNAL_API_URL=http://backend:8000
    environment:
      - INTERNAL_API_URL=http://backend:8000
    ports:
      - "3000:3000"

volumes:
  whylowdps-db-data:
